export type BotcRoleInfo = {
  roleName: string
  description: string
}

const normalizeRoleKey = (value: string): string =>
  String(value || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "")

const BOTC_ROLE_INFO_LIST: BotcRoleInfo[] = [
  { roleName: `Acrobat`, description: `If you die at night, an evil player might die too.` },
  { roleName: `Al-Hadikhia`, description: `Each night*, choose three players. Each in turn must choose to live or die. If a good player chooses to die, their team loses. (*After the first night.)` },
  { roleName: `Alchemist`, description: `You gain the ability of a Minion that is not in play (you remain good).` },
  { roleName: `Amnesiac`, description: `You have an ability, but you don't know what it is. You can privately guess it each day to learn how accurate you are.` },
  { roleName: `Artist`, description: `Once per game, during the day, you may ask the Storyteller any yes/no question.` },
  { roleName: `Assassin`, description: `Once per game, at night, choose a player: they die (even if normally protected).` },
  { roleName: `Atheist`, description: `The Storyteller may break the rules. If good players execute the Storyteller, good wins.` },
  { roleName: `Balloonist`, description: `Each night, learn a player of a different character type than those you have previously learned.` },
  { roleName: `Banshee`, description: `If you die by execution, you may publicly claim Banshee. While you are alive after that claim, your vote counts as two.` },
  { roleName: `Barber`, description: `If you die at night, the Demon may choose two players to swap characters.` },
  { roleName: `Boffin`, description: `The Demon has an additional Minion ability (from one not in play).` },
  { roleName: `Boomdandy`, description: `If executed, all but three players die immediately.` },
  { roleName: `Bounty Hunter`, description: `You start knowing one evil player. A good player is turned evil.` },
  { roleName: `Butler`, description: `Each night, choose a player. Tomorrow, you may only vote if they are voting.` },
  { roleName: `Cannibal`, description: `Each day, you gain the ability of the Townsfolk executed that day (you might be drunk).` },
  { roleName: `Cerenovus`, description: `Each night, choose a player and a character; they are "mad" they are that character tomorrow or may be executed.` },
  { roleName: `Chambermaid`, description: `Each night, choose two players; learn how many woke tonight due to their ability.` },
  { roleName: `Chef`, description: `You learn how many pairs of evil players are sitting next to each other.` },
  { roleName: `Choirboy`, description: `If the King is executed, you learn the Demon.` },
  { roleName: `Clockmaker`, description: `You learn how many players sit between the Demon and their nearest Minion.` },
  { roleName: `Courtier`, description: `Once per game, at night, choose a character; they are drunk for 3 days and nights.` },
  { roleName: `Cult Leader`, description: `Each night, choose a player: they become your alignment. If all living players are your alignment, your team wins.` },
  { roleName: `Damsel`, description: `If a Minion publicly guesses that you are the Damsel, your team loses.` },
  { roleName: `Devil's Advocate`, description: `Each night, choose a player: if executed tomorrow, they do not die.` },
  { roleName: `Dreamer`, description: `Each night, choose a player. You learn one good and one evil character they might be.` },
  { roleName: `Drunk`, description: `You think you are a Townsfolk, but your ability does not work correctly.` },
  { roleName: `Empath`, description: `Each night, learn how many of your two neighbors are evil.` },
  { roleName: `Engineer`, description: `Once per game, at night, change which Minions or Demon are in play to others of your choice.` },
  { roleName: `Evil Twin`, description: `You and another player know each other. One of you is evil and one is good. If the good Twin dies, evil wins.` },
  { roleName: `Exorcist`, description: `Each night, choose a player: if they are the Demon, they do not wake tonight.` },
  { roleName: `Fang Gu`, description: `Each night, choose a player: they die. The first time you kill an Outsider, they become an evil Fang Gu and you die instead.` },
  { roleName: `Farmer`, description: `If you die at night, an Outsider becomes a Townsfolk.` },
  { roleName: `Fearmonger`, description: `Choose a player. If they die while nominated by you, your team wins.` },
  { roleName: `Fisherman`, description: `Once per game, during the day, you may ask the Storyteller for advice to help your team.` },
  { roleName: `Flowergirl`, description: `Each night, learn if the Demon voted today.` },
  { roleName: `Fool`, description: `The first time you would die, you do not die.` },
  { roleName: `Fortune Teller`, description: `Each night, choose two players; learn if either is the Demon (with one false positive in play).` },
  { roleName: `Gambler`, description: `Each night, choose a player and guess their character; if wrong, you die.` },
  { roleName: `General`, description: `Each night, learn which alignment the Storyteller believes is winning.` },
  { roleName: `Goblin`, description: `If you publicly claim to be the Goblin and are executed that day, evil wins.` },
  { roleName: `Godfather`, description: `You start knowing the Outsiders. If an Outsider dies by execution, someone dies that night.` },
  { roleName: `Golem`, description: `You may nominate only once per game. If that nomination executes a player and they are not the Demon, you die.` },
  { roleName: `Goon`, description: `Each night, the first player to choose you with their ability makes you drunk and changes your alignment.` },
  { roleName: `Gossip`, description: `Each day, make a public statement; if it is true, a player dies that night.` },
  { roleName: `Grandmother`, description: `You start knowing a good character and who it is. If they die at night, you die too.` },
  { roleName: `Harpy`, description: `Each night, choose two players: tomorrow, they are mad that the other is evil or may be executed.` },
  { roleName: `Hatter`, description: `If you are executed, the Minions and Demon may change to different characters.` },
  { roleName: `Heretic`, description: `Good wins if the Demon is alive at the end of the game. Evil wins if the Demon dies.` },
  { roleName: `Hermit`, description: `You may register as evil and/or as a Minion or Demon, even though you are good.` },
  { roleName: `High Priestess`, description: `Each night, the Storyteller points to the player you should talk to most.` },
  { roleName: `Huntsman`, description: `Once per game, at night, choose a player. If they are the Damsel, they become a Townsfolk.` },
  { roleName: `Imp`, description: `Each night*, choose a player: they die. If you kill yourself this way, a Minion becomes the Imp. (*Except the first night.)` },
  { roleName: `Innkeeper`, description: `Each night, choose two players: they cannot die tonight, but one is drunk until tomorrow dusk.` },
  { roleName: `Investigator`, description: `You start knowing that one of two players is a particular Minion.` },
  { roleName: `Juggler`, description: `On your first day, publicly guess players' characters; that night, learn how many were correct.` },
  { roleName: `Kazali`, description: `On the first night, choose players to become Minions of your choice.` },
  { roleName: `King`, description: `You start knowing two players, one of whom is the Demon. If you die at night, your team loses.` },
  { roleName: `Klutz`, description: `When you die by execution, publicly choose a player: if they are evil, your team loses.` },
  { roleName: `Knight`, description: `You start knowing two players who are not the Demon.` },
  { roleName: `Legion`, description: `All evil players are Legion. Each night, a player may die. (There is no single Demon; evil wins if they outnumber good.)` },
  { roleName: `Leviathan`, description: `If the Demon is not executed by day 5, evil wins. There are no night deaths.` },
  { roleName: `Librarian`, description: `You start knowing that one of two players is a particular Outsider.` },
  { roleName: `Lil' Monsta`, description: `Each night, Minions choose a babysitter. The babysitter is the Demon and chooses who dies.` },
  { roleName: `Lleech`, description: `Each night*, choose a player: they die. On the first night, choose a player: they are poisoned. If they die, you die instead. (*Except the first night.)` },
  { roleName: `Lord of Typhoon`, description: `Each night, choose a player: they die. Players killed by the Demon may nominate immediately before dying.` },
  { roleName: `Lunatic`, description: `You think you are the Demon, but you are not.` },
  { roleName: `Lycanthrope`, description: `Each night, choose a player; if they are evil, they die. If they are good, you die.` },
  { roleName: `Magician`, description: `The Demon does not know you are in play and believes you are evil.` },
  { roleName: `Marionette`, description: `You are evil and poisoned, but think you are good.` },
  { roleName: `Mastermind`, description: `If the Demon dies, play continues for one extra day. If good does not execute someone that day, evil wins.` },
  { roleName: `Mathematician`, description: `Each night, learn how many abilities malfunctioned today.` },
  { roleName: `Mayor`, description: `If only three players live and no execution occurs, your team wins.` },
  { roleName: `Mezepheles`, description: `You know a secret word. The first good player to say it becomes evil.` },
  { roleName: `Minstrel`, description: `When a Minion is executed, all other players are drunk until dusk.` },
  { roleName: `Monk`, description: `Each night, choose a player; they cannot die tonight (except by execution).` },
  { roleName: `Moonchild`, description: `When you die, choose a player: if they are good, they die.` },
  { roleName: `Mutant`, description: `If you publicly claim to be an Outsider, you may be executed.` },
  { roleName: `Nightwatchman`, description: `Once per game, at night, choose a player: they learn who you are.` },
  { roleName: `No Dashii`, description: `Each night*, choose a player: they die. Your Townsfolk neighbors are poisoned. (*Except the first night.)` },
  { roleName: `Noble`, description: `You start knowing three players, one of whom is evil.` },
  { roleName: `Ogre`, description: `Each night, choose a player. You change alignment to match theirs.` },
  { roleName: `Ojo`, description: `Each night*, choose a character. If that character is in play, that player dies. (*Except the first night.)` },
  { roleName: `Oracle`, description: `Each night, learn how many dead players are evil.` },
  { roleName: `Organ Grinder`, description: `While you are alive, players vote with eyes closed and results are hidden.` },
  { roleName: `Pacifist`, description: `If only good players voted to execute someone, the execution may fail.` },
  { roleName: `Philosopher`, description: `Once per game, gain a Townsfolk ability; you are drunk for the rest of the game.` },
  { roleName: `Pit-Hag`, description: `ach night, choose a player and a character: they become that character.` },
  { roleName: `Pixie`, description: `You start knowing a Townsfolk role in play. If you publicly claim it, you gain its ability.` },
  { roleName: `Plague Doctor`, description: `If you die by execution, the Storyteller gains a Minion ability.` },
  { roleName: `Po`, description: `Each night, you may choose no one. If you choose no one, then the next night you choose two players; they die.` },
  { roleName: `Poisoner`, description: `Each night, choose a player: they are poisoned tonight and tomorrow day.` },
  { roleName: `Politician`, description: `If you were instrumental in your team losing, you may change alignment.` },
  { roleName: `Poppy Grower`, description: `Minions and Demon do not know each other while you are alive.` },
  { roleName: `Preacher`, description: `Each night, choose a player: if they are a Minion, they lose their ability.` },
  { roleName: `Princess`, description: `If you die by execution, the Demon learns who you are.` },
  { roleName: `Professor`, description: `Once per game, at night, choose a dead player; if they are good, they return to life.` },
  { roleName: `Psychopath`, description: `Each day, you may publicly kill a player. If you kill a good player, you might die.` },
  { roleName: `Pukka`, description: `Each night, choose a player: they are poisoned. The previously poisoned player dies and is no longer poisoned.` },
  { roleName: `Puzzlemaster`, description: `One player is drunk. Once per game, guess who it is: if correct, you learn the Demon.` },
  { roleName: `Ravenkeeper`, description: `If you die at night, you learn a player's character.` },
  { roleName: `Recluse`, description: `You may register as evil and/or as a Minion or Demon, even though you are good.` },
  { roleName: `Riot`, description: `Each day, nominations are immediate and may cause instant victory depending on alignment. (Kills and victory conditions occur rapidly and publicly.)` },
  { roleName: `Sailor`, description: `Each night, choose a player; either you or they is drunk until dusk, and neither can die that night.` },
  { roleName: `Saint`, description: `If you die by execution, your team loses.` },
  { roleName: `Savant`, description: `Each day, you learn two statements: one is true, one is false.` },
  { roleName: `Scarlet Woman`, description: `If the Demon dies while five or more players are alive, you become the Demon.` },
  { roleName: `Seamstress`, description: `Once per game, learn whether two players are the same alignment.` },
  { roleName: `Shabaloth`, description: `Each night*, choose two players: they die. A dead player might be resurrected. (*Except the first night.)` },
  { roleName: `Shugenja`, description: `You learn whether evil players are mostly clockwise or counterclockwise from you.` },
  { roleName: `Slayer`, description: `Once per game, publicly choose a player: if they are the Demon, they die.` },
  { roleName: `Snake Charmer`, description: `Each night, choose a player: if they are the Demon, you swap characters.` },
  { roleName: `Snitch`, description: `Minions start knowing three good roles that are in play.` },
  { roleName: `Soldier`, description: `You cannot be killed by the Demon.` },
  { roleName: `Spy`, description: `Each night, you see the Grimoire. You may register as good and as a Townsfolk or Outsider.` },
  { roleName: `Steward`, description: `You start knowing one player who is good.` },
  { roleName: `Summoner`, description: `On the third night, choose a player: they become an evil Demon of your choice.` },
  { roleName: `Sweetheart`, description: `When you die, one player becomes drunk.` },
  { roleName: `Tea Lady`, description: `If both your neighbors are good, they cannot die.` },
  { roleName: `Tinker`, description: `You might die at any time.` },
  { roleName: `Town Crier`, description: `Each night, learn if a Minion nominated today.` },
  { roleName: `Undertaker`, description: `Each night, learn the character of the player executed today.` },
  { roleName: `Vigormortis`, description: `Each night*, choose a player: they die. A dead Minion retains their ability. (*Except the first night.)` },
  { roleName: `Village Idiot`, description: `Each night, learn a player's alignment.` },
  { roleName: `Virgin`, description: `The first Townsfolk to nominate you is executed.` },
  { roleName: `Vizier`, description: `You are publicly known to be evil. You cannot be executed. If the Demon dies, evil wins.` },
  { roleName: `Vortox`, description: `Each night*, choose a player: they die. Townsfolk information is false. If no execution occurs during the day, evil wins. (*Except the first night.)` },
  { roleName: `Washerwoman`, description: `You start knowing that one of two players is a particular Townsfolk.` },
  { roleName: `Widow`, description: `On the first night, poison a Townsfolk. You see the Grimoire. One good player knows a Widow is in play.` },
  { roleName: `Witch`, description: `Each night, choose a player: if they nominate tomorrow, they die.` },
  { roleName: `Wizard`, description: `Each night, choose a player and guess their character: if correct, they die.` },
  { roleName: `Wraith`, description: `Once per game, at night, choose a player: they die.` },
  { roleName: `Xaan`, description: `Each night*, choose a player: if they are good, they might die; if evil, you might die instead. (*Exact timing may depend on script wording.)` },
  { roleName: `Yaggababble`, description: `Each day, if you do not say a specific word or phrase, a player dies that night. (You privately learn the word/phrase each night.)` },
  { roleName: `Zealot`, description: `If there are five or more players alive, you must vote for every execution.` },
  { roleName: `Zombuul`, description: `Each night*, choose a player: they die. The first time you die, you remain alive but appear dead. (*Except the first night.)` },
]

const BOTC_ROLE_INFO_BY_KEY = BOTC_ROLE_INFO_LIST.reduce<Record<string, BotcRoleInfo>>((acc, roleInfo) => {
  acc[normalizeRoleKey(roleInfo.roleName)] = roleInfo
  return acc
}, {})

const BOTC_ROLE_INFO_ALIASES: Record<string, string> = {
  fearmongerer: "fearmonger",
  lordoftyphon: "lordoftyphoon",
  lyncanthrope: "lycanthrope",
}

export const getBotcRoleInfo = (roleId: string): BotcRoleInfo | null => {
  const key = normalizeRoleKey(roleId)
  if (!key) return null

  const resolvedKey = BOTC_ROLE_INFO_ALIASES[key] ?? key
  return BOTC_ROLE_INFO_BY_KEY[resolvedKey] ?? null
}
